/*
 * This file is generated by jOOQ.
 */
package com.endsound.trpg.backend.character.jooq.tables.daos;


import com.endsound.trpg.backend.character.jooq.tables.Character;
import com.endsound.trpg.backend.character.jooq.tables.records.CharacterRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 角色
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CharacterDao extends DAOImpl<CharacterRecord, com.endsound.trpg.backend.character.jooq.tables.pojos.Character, Integer> {

    /**
     * Create a new CharacterDao without any configuration
     */
    public CharacterDao() {
        super(Character.CHARACTER, com.endsound.trpg.backend.character.jooq.tables.pojos.Character.class);
    }

    /**
     * Create a new CharacterDao with an attached configuration
     */
    public CharacterDao(Configuration configuration) {
        super(Character.CHARACTER, com.endsound.trpg.backend.character.jooq.tables.pojos.Character.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.endsound.trpg.backend.character.jooq.tables.pojos.Character object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.endsound.trpg.backend.character.jooq.tables.pojos.Character> fetchById(Integer... values) {
        return fetch(Character.CHARACTER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.endsound.trpg.backend.character.jooq.tables.pojos.Character fetchOneById(Integer value) {
        return fetchOne(Character.CHARACTER.ID, value);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public List<com.endsound.trpg.backend.character.jooq.tables.pojos.Character> fetchByData(Object... values) {
        return fetch(Character.CHARACTER.DATA, values);
    }

    /**
     * Fetch records that have <code>belong_user_id IN (values)</code>
     */
    public List<com.endsound.trpg.backend.character.jooq.tables.pojos.Character> fetchByBelongUserId(Integer... values) {
        return fetch(Character.CHARACTER.BELONG_USER_ID, values);
    }
}
