/*
 * This file is generated by jOOQ.
 */
package com.endsound.trpg.security.jooq;


import com.endsound.trpg.security.jooq.tables.Group;
import com.endsound.trpg.security.jooq.tables.MapGroupRole;
import com.endsound.trpg.security.jooq.tables.MapUserGroup;
import com.endsound.trpg.security.jooq.tables.Role;
import com.endsound.trpg.security.jooq.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in utakaze
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 群組
     */
    public static final Group GROUP = com.endsound.trpg.security.jooq.tables.Group.GROUP;

    /**
     * The table <code>utakaze.map_group_role</code>.
     */
    public static final MapGroupRole MAP_GROUP_ROLE = com.endsound.trpg.security.jooq.tables.MapGroupRole.MAP_GROUP_ROLE;

    /**
     * 使用者群組對應
     */
    public static final MapUserGroup MAP_USER_GROUP = com.endsound.trpg.security.jooq.tables.MapUserGroup.MAP_USER_GROUP;

    /**
     * 角色
     */
    public static final Role ROLE = com.endsound.trpg.security.jooq.tables.Role.ROLE;

    /**
     * 使用者資訊
     */
    public static final User USER = com.endsound.trpg.security.jooq.tables.User.USER;
}
