/*
 * This file is generated by jOOQ.
 */
package com.endsound.trpg.security.jooq.tables.daos;


import com.endsound.trpg.security.jooq.tables.MapGroupRole;
import com.endsound.trpg.security.jooq.tables.records.MapGroupRoleRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MapGroupRoleDao extends DAOImpl<MapGroupRoleRecord, com.endsound.trpg.security.jooq.tables.pojos.MapGroupRole, Record2<Integer, Integer>> {

    /**
     * Create a new MapGroupRoleDao without any configuration
     */
    public MapGroupRoleDao() {
        super(MapGroupRole.MAP_GROUP_ROLE, com.endsound.trpg.security.jooq.tables.pojos.MapGroupRole.class);
    }

    /**
     * Create a new MapGroupRoleDao with an attached configuration
     */
    public MapGroupRoleDao(Configuration configuration) {
        super(MapGroupRole.MAP_GROUP_ROLE, com.endsound.trpg.security.jooq.tables.pojos.MapGroupRole.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<Integer, Integer> getId(com.endsound.trpg.security.jooq.tables.pojos.MapGroupRole object) {
        return compositeKeyRecord(object.getGroupId(), object.getRoleId());
    }

    /**
     * Fetch records that have <code>group_id IN (values)</code>
     */
    public List<com.endsound.trpg.security.jooq.tables.pojos.MapGroupRole> fetchByGroupId(Integer... values) {
        return fetch(MapGroupRole.MAP_GROUP_ROLE.GROUP_ID, values);
    }

    /**
     * Fetch records that have <code>role_id IN (values)</code>
     */
    public List<com.endsound.trpg.security.jooq.tables.pojos.MapGroupRole> fetchByRoleId(Integer... values) {
        return fetch(MapGroupRole.MAP_GROUP_ROLE.ROLE_ID, values);
    }
}
