/*
 * This file is generated by jOOQ.
 */
package com.endsound.trpg.security.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * 使用者群組對應
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MapUserGroup implements Serializable {

    private static final long serialVersionUID = -1306268393;

    private Integer userId;
    private Integer groupId;

    public MapUserGroup() {}

    public MapUserGroup(MapUserGroup value) {
        this.userId = value.userId;
        this.groupId = value.groupId;
    }

    public MapUserGroup(
        Integer userId,
        Integer groupId
    ) {
        this.userId = userId;
        this.groupId = groupId;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public MapUserGroup setUserId(Integer userId) {
        this.userId = userId;
        return this;
    }

    public Integer getGroupId() {
        return this.groupId;
    }

    public MapUserGroup setGroupId(Integer groupId) {
        this.groupId = groupId;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MapUserGroup (");

        sb.append(userId);
        sb.append(", ").append(groupId);

        sb.append(")");
        return sb.toString();
    }
}
