/*
 * This file is generated by jOOQ.
 */
package com.endsound.trpg.backend.character.jooq;


import com.endsound.trpg.backend.character.jooq.tables.Character;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>utakaze</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CHARACTER_FK_CHARACTER_USER = Indexes0.CHARACTER_FK_CHARACTER_USER;
    public static final Index CHARACTER_PRIMARY = Indexes0.CHARACTER_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index CHARACTER_FK_CHARACTER_USER = Internal.createIndex("fk_character_user", Character.CHARACTER, new OrderField[] { Character.CHARACTER.BELONG_USER_ID }, false);
        public static Index CHARACTER_PRIMARY = Internal.createIndex("PRIMARY", Character.CHARACTER, new OrderField[] { Character.CHARACTER.ID }, true);
    }
}
