/*
 * This file is generated by jOOQ.
 */
package com.endsound.trpg.backend.character.jooq;


import com.endsound.trpg.backend.character.jooq.tables.Character;
import com.endsound.trpg.backend.character.jooq.tables.records.CharacterRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>utakaze</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<CharacterRecord, Integer> IDENTITY_CHARACTER = Identities0.IDENTITY_CHARACTER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CharacterRecord> KEY_CHARACTER_PRIMARY = UniqueKeys0.KEY_CHARACTER_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<CharacterRecord, Integer> IDENTITY_CHARACTER = Internal.createIdentity(Character.CHARACTER, Character.CHARACTER.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<CharacterRecord> KEY_CHARACTER_PRIMARY = Internal.createUniqueKey(Character.CHARACTER, "KEY_character_PRIMARY", Character.CHARACTER.ID);
    }
}
