/*
 * This file is generated by jOOQ.
 */
package com.endsound.trpg.backend.character.jooq;


import com.endsound.trpg.backend.character.jooq.tables.Character;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in utakaze
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 角色
     */
    public static final Character CHARACTER = com.endsound.trpg.backend.character.jooq.tables.Character.CHARACTER;
}
