/*
 * This file is generated by jOOQ.
 */
package com.endsound.trpg.frontend.user.jooq;


import com.endsound.trpg.frontend.user.jooq.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in utakaze
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 使用者資訊
     */
    public static final User USER = com.endsound.trpg.frontend.user.jooq.tables.User.USER;
}
