/*
 * This file is generated by jOOQ.
 */
package com.endsound.trpg.backend.character.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * 角色
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Character implements Serializable {

    private static final long serialVersionUID = 1766740728;

    private Integer id;
    private Object  data;
    private Integer belongUserId;

    public Character() {}

    public Character(Character value) {
        this.id = value.id;
        this.data = value.data;
        this.belongUserId = value.belongUserId;
    }

    public Character(
        Integer id,
        Object  data,
        Integer belongUserId
    ) {
        this.id = id;
        this.data = data;
        this.belongUserId = belongUserId;
    }

    public Integer getId() {
        return this.id;
    }

    public Character setId(Integer id) {
        this.id = id;
        return this;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public Object getData() {
        return this.data;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public Character setData(Object data) {
        this.data = data;
        return this;
    }

    public Integer getBelongUserId() {
        return this.belongUserId;
    }

    public Character setBelongUserId(Integer belongUserId) {
        this.belongUserId = belongUserId;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Character (");

        sb.append(id);
        sb.append(", ").append(data);
        sb.append(", ").append(belongUserId);

        sb.append(")");
        return sb.toString();
    }
}
